services:
  backend:
    build: ./app
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build: ./chat_pure_react
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - HOST_IP=${HOST_IP}

networks:
  app-network:
    driver: bridge